-- Create address table
CREATE TABLE address (
    ADDRESS_ID BIGINT PRIMARY KEY,
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(10,8),
    STREET_ADDRESS VARCHAR(100),
    CITY VARCHAR(50),
    STATE CHAR(2),
    COUNTY VARCHAR(50)
);

-- Create customer table
CREATE TABLE customer (
    INDIVIDUAL_ID BIGINT PRIMARY KEY,
    ADDRESS_ID BIGINT NOT NULL,
    CURR_ANN_AMT DECIMAL(10,2),
    DAYS_TENURE INT,
    CUST_ORIG_DATE DATE,
    AGE_IN_YEARS DECIMAL(5,2),
    DATE_OF_BIRTH DATE,
    SOCIAL_SECURITY_NUMBER VARCHAR(15),
    CONSTRAINT fk_address FOREIGN KEY (ADDRESS_ID) REFERENCES address (ADDRESS_ID)
);

-- Create demographic table
CREATE TABLE demographic (
    INDIVIDUAL_ID BIGINT PRIMARY KEY,
    INCOME INT,
    HAS_CHILDREN BOOLEAN,
    LENGTH_OF_RESIDENCE INT,
    MARITAL_STATUS VARCHAR(10),
    HOME_MARKET_VALUE VARCHAR(50),
    HOME_OWNER BOOLEAN,
    COLLEGE_DEGREE BOOLEAN,
    GOOD_CREDIT BOOLEAN,
    CONSTRAINT fk_customer FOREIGN KEY (INDIVIDUAL_ID) REFERENCES customer (INDIVIDUAL_ID)
);

-- Create termination table
CREATE TABLE termination (
    INDIVIDUAL_ID BIGINT PRIMARY KEY,
    ACCT_SUSPD_DATE DATE,
    CONSTRAINT fk_customer_termination FOREIGN KEY (INDIVIDUAL_ID) REFERENCES customer (INDIVIDUAL_ID)
);

-- Create autoinsurance_churn table
CREATE TABLE autoinsurance_churn (
    INDIVIDUAL_ID BIGINT,
    ADDRESS_ID BIGINT,
    CURR_ANN_AMT DECIMAL(10,2),
    DAYS_TENURE INT,
    CUST_ORIG_DATE DATE,
    AGE_IN_YEARS DECIMAL(5,2),
    DATE_OF_BIRTH DATE,
    LATITUDE DECIMAL(10,8),
    LONGITUDE DECIMAL(10,8),
    CITY VARCHAR(50),
    STATE CHAR(2),
    COUNTY VARCHAR(50),
    INCOME INT,
    HAS_CHILDREN BOOLEAN,
    LENGTH_OF_RESIDENCE INT,
    MARITAL_STATUS VARCHAR(10),
    HOME_MARKET_VALUE VARCHAR(50),
    HOME_OWNER BOOLEAN,
    COLLEGE_DEGREE BOOLEAN,
    GOOD_CREDIT BOOLEAN,
    ACCT_SUSPD_DATE DATE,
    CHURN BOOLEAN,
    CONSTRAINT fk_customer_autoinsurance FOREIGN KEY (INDIVIDUAL_ID) REFERENCES customer (INDIVIDUAL_ID),
    CONSTRAINT fk_address_autoinsurance FOREIGN KEY (ADDRESS_ID) REFERENCES address (ADDRESS_ID)
);
